name: Update Zag Dependencies

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Upgrade Dependencies
        run: pnpm deps

      - name: Setup Git
        run: |
          git config --global user.name "Segun Adebayo"
          git config --global user.email "joseshegs@gmail.com"

      - name: Commit Changes
        run: |
          git add . && git commit -m "chore: update zag dependencies"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "chore: update zag versions"
          delete-branch: true
          branch: chore/update-deps
